---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: zookeeper1
  namespace: erp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
        # 后续service通过该标签选择指定的pod
        server-id: "1"
    spec:
      containers:
        - name: server
          image: harbor.k8s.com/erp/zookeeper:uvxb8yrg_20220425_154023
          imagePullPolicy: Always
          env:
            # 此处定义的环境变量即为容器启动时执行的脚本entrypoint.sh中使用的环境变量
            - name: MYID
              value: "1"
            - name: SERVERS
              value: "zookeeper1,zookeeper2,zookeeper3"
            - name: JVMFLAGS
              value: "-Xmx1G"
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888
          volumeMounts:
            # 此处的挂载点为zookeeper保存数据的路径 在构建镜像时 /conf/zoo.cfg中定义了该路径
            - mountPath: "/zookeeper/data"
              name: zookeeper-datadir-pvc-1
      volumes:
        - name: zookeeper-datadir-pvc-1
          persistentVolumeClaim:
            # 通过pvc的名称指定要绑定的pvc
            claimName: zookeeper-datadir-pvc-1
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: zookeeper2
  namespace: erp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
        # 后续service通过该标签选择指定的pod
        server-id: "2"
    spec:
      containers:
        - name: server
          image: harbor.k8s.com/erp/zookeeper:uvxb8yrg_20220425_154023
          imagePullPolicy: Always
          env:
            # 此处定义的环境变量即为容器启动时执行的脚本entrypoint.sh中使用的环境变量
            - name: MYID
              value: "2"
            - name: SERVERS
              value: "zookeeper1,zookeeper2,zookeeper3"
            - name: JVMFLAGS
              value: "-Xmx1G"
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888
          volumeMounts:
            # 此处的挂载点为zookeeper保存数据的路径 在构建镜像时 /conf/zoo.cfg中定义了该路径
            - mountPath: "/zookeeper/data"
              name: zookeeper-datadir-pvc-2
      volumes:
        - name: zookeeper-datadir-pvc-2
          persistentVolumeClaim:
            # 通过pvc的名称指定要绑定的pvc
            claimName: zookeeper-datadir-pvc-2
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: zookeeper3
  namespace: erp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
        # 后续service通过该标签选择指定的pod
        server-id: "3"
    spec:
      containers:
        - name: server
          image: harbor.k8s.com/erp/zookeeper:uvxb8yrg_20220425_154023
          imagePullPolicy: Always
          env:
            # 此处定义的环境变量即为容器启动时执行的脚本entrypoint.sh中使用的环境变量
            - name: MYID
              value: "3"
            - name: SERVERS
              value: "zookeeper1,zookeeper2,zookeeper3"
            - name: JVMFLAGS
              value: "-Xmx1G"
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888
          volumeMounts:
            # 此处的挂载点为zookeeper保存数据的路径 在构建镜像时 /conf/zoo.cfg中定义了该路径
            - mountPath: "/zookeeper/data"
              name: zookeeper-datadir-pvc-3
      volumes:
        - name: zookeeper-datadir-pvc-3
          persistentVolumeClaim:
            # 通过pvc的名称指定要绑定的pvc
            claimName: zookeeper-datadir-pvc-3