kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: erp-tomcat-webapp-deployment-label
  name: erp-tomcat-webapp-deployment
  namespace:
    erp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erp-tomcat-webapp-selector
  template:
    metadata:
      labels:
        app: erp-tomcat-webapp-selector
    spec:
      containers:
        - name: erp-tomcat-webapp-container
          image: harbor.k8s.com/erp/tomcat-webapp:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          resources:
            limits:
              cpu: 1
              memory: "512Mi"
            requests:
              cpu: 500m
              memory: "512Mi"
          volumeMounts:
            - name: tomcat-webapp-images
              mountPath: /usr/local/nginx/html/webapp/images
              readOnly: false
            - name: tomcat-webapp-static
              mountPath: /usr/local/nginx/html/webapp/static
              readOnly: false
      volumes:
        - name: tomcat-webapp-images
          nfs:
            server: 172.16.1.189
            path: /data/k8sdata/nginx-webapp/images
        - name: tomcat-webapp-static
          nfs:
            server: 172.16.1.189
            path: /data/k8sdata/nginx-webapp/static
