apiVersion: v1
kind: Service
metadata:
  name: dubbo-admin-service
  namespace: erp
  labels:
    app: dubbo-admin-service
spec:
  selector:
    app: dubbo-admin
  type: NodePort
  ports:
    - name: dubbo-admin-8080
      port: 8080
      targetPort: 8080
      nodePort: 30088