common_lb_config:
  zone_aware_lb_config:
  # 值类型为百分比 
  # 用于配置在多大比例的请求流量上启用区域感知路由机制
  # 默认为100%
  routing_enabled: "{...}", 
  # 配置区域感知路由所需的最小上游集群大小
  # 上游集群大小小于指定的值时即使配置了区域感知路由也不会执行区域感知路由
  # 默认值为6 可用值为64位整数
  min_cluster_size: "{...}" 