apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # PVC的名称
  name: mysql-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  # StorageClass的名称
  storageClassName: ceph-storage-class-k8s-user
  resources:
    requests:
      storage: '5Gi'