kind: Service
apiVersion: v1
metadata:
  labels:
    app: mysql-service-label
  name: mysql-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 3306
      protocol: TCP
      targetPort: 3306
      nodePort: 43306
  selector:
    app: mysql