apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ceph-secret-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ng-secret-deploy-80
  template:
    metadata:
      labels:
        app: ng-secret-deploy-80
    spec:
      containers:
        - name: ng-secret-deploy-80
          image: harbor.k8s.com/erp/nginx:1.16.1
          ports:
            - containerPort: 80
          volumeMounts:
            - name: rbd-data1
              mountPath: /data
      volumes:
        - name: rbd-data1
          rbd:
            monitors:
              - '192.168.0.165:6789'
              - '192.168.0.166:6789'
              - '192.168.0.167:6789'
            pool: k8s-rbd-pool1
            image: k8s-img-img1
            fsType: ext4
            readOnly: false
            user: k8s-user
            # 使用secret认证
            secretRef:
              name: ceph-secret-k8s-user