apiVersion: v1
kind: Pod
metadata: 
  name: busybox
  namespace: default
spec:
  containers:
    - image: busybox
      command:
        - sleep
        - "3600"
      imagePullPolicy: Always
      name: busybox
      volumeMounts:
        - name: rbd-data1
          mountPath: /data
  volumes:
    - name: rbd-data1
      rbd:
        monitors:
          - '192.168.0.165:6789'
          - '192.168.0.166:6789'
          - '192.168.0.167:6789'
        pool: k8s-rbd-pool1
        image: k8s-img-img1
        fsType: ext4
        readOnly: false
        user: k8s-user
        keyring: /etc/ceph/ceph.client.k8s-user.keyring