apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-1
  namespace: erp
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/k8sdata/erp/redis-datadir-1
    server: 172.16.1.189