apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc-1 
  namespace: erp
spec:
  volumeName: redis-pv-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
