apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
 default: |
    server {
       listen       80;
       server_name  www.mysite.com;
       index        index.html;

       location / {
           root /data/nginx/html;
           if (!-e $request_filename) {
               rewrite ^/(.*) /index.html last;
           }
       }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ng-deploy-80
  template:
    metadata:
      labels:
        app: ng-deploy-80
    spec:
      containers:
      - name: ng-deploy-80
        image: harbor.k8s.com/erp/nginx:1.16.1  
        ports:
        - containerPort: 80
        # volumeMounts的声明级别是针对container的
        volumeMounts:
        - mountPath: /data/nginx/html
          name: nginx-static-dir
          # 将名为nginx-config的volume挂载到当前容器中的/etc/nginx/conf.d上
        - name: nginx-config
          mountPath:  /etc/nginx/conf.d
      # volume的声明级别是针对pod的    
      volumes:
      - name: nginx-static-dir
        hostPath:
          path: /data/erp
      - name: nginx-config
        configMap:
          # configMap的名称
          name: nginx-config
          items:
               # 此处的default 就是configMap.data
             - key: default
               # 容器中的挂载点
               path: mysite.conf

---
apiVersion: v1
kind: Service
metadata:
  name: ng-deploy-80
spec:
  ports:
  - name: http
    port: 81
    targetPort: 80
    nodePort: 30019
    protocol: TCP
  type: NodePort
  selector:
    app: ng-deploy-80