kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: erp-gray-released-deployment-v2
  name: erp-gray-released-deployment-v2
  namespace: erp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erp-gray-released-app
      version: v2
  template:
    metadata:
      labels:
        app: erp-gray-released-app
        version: v2
    spec:
      containers:
        - name: erp-gray-released-app-container
          image: harbor.k8s.com/erp/gray-released-app:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
            - containerPort: 443
              protocol: TCP
              name: https