apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-datadir-5
  namespace: erp
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/k8sdata/erp/mysql-datadir-5
    server: 172.16.1.189