kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: erp-consumer
  name: erp-consumer-deployment
  namespace: erp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erp-consumer
  template:
    metadata:
      labels:
        app: erp-consumer
    spec:
      containers:
      - name: erp-consumer-container
        image: harbor.k8s.com/erp/dubbo-demo-consumer:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
          name: http