apiVersion: apps/v1
kind: Deployment
metadata:
  name: limit-test-deployment
  namespace: erp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: limit-test-pod
  template:
    metadata:
      labels:
        app: limit-test-pod
    spec:
      containers:
      - name: limit-test-container
        image: harbor.k8s.com/limit-case/docker-stress-ng:v1
        resources:
          limits:
            memory: "512Mi"
          requests:
            memory: "100Mi"
        # 此处的参数定义了只能使用2个CPU内核 且该容器最多使用512M的内存 2表示2个线程 256M表示每个线程最多占用的内存
        args: ["--vm", "2", "--vm-bytes", "256M"]
