kind: Service
apiVersion: v1
metadata:
  labels:
    app: erp-provider
  name: erp-provider-service
  namespace: erp
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 20880
  selector:
    app: erp-provider