apiVersion: v1
kind: Service
metadata:
  name: nginx-tcp-probe-service
spec:
  ports:
  - name: http
    port: 81
    targetPort: 80
    nodePort: 40012
    protocol: TCP
  type: NodePort
  selector:
    app: nginx-tcp-probe-80