---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # pvc的名称 后续pod通过pvc的名称和指定的pvc产生绑定关系
  name: zookeeper-datadir-pvc-1
  namespace: erp
spec:
  accessModes:
    - ReadWriteOnce
    # pv的名称 pvc通过pv的名称和pv产生绑定关系
  volumeName: zookeeper-datadir-pv-1
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # pvc的名称 后续pod通过pvc的名称和指定的pvc产生绑定关系
  name: zookeeper-datadir-pvc-2
  namespace: erp
spec:
  accessModes:
    - ReadWriteOnce
    # pv的名称 pvc通过pv的名称和pv产生绑定关系
  volumeName: zookeeper-datadir-pv-2
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # pvc的名称 后续pod通过pvc的名称和指定的pvc产生绑定关系
  name: zookeeper-datadir-pvc-3
  namespace: erp
spec:
  accessModes:
    - ReadWriteOnce
    # pv的名称 pvc通过pv的名称和pv产生绑定关系
  volumeName: zookeeper-datadir-pv-3
  resources:
    requests:
      storage: 1Gi