kind: Service
apiVersion: v1
metadata:
  labels:
    app: erp-jenkins
  name: erp-jenkins-service
  namespace: erp
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 38080
  selector:
    app: erp-jenkins