apiVersion: v1
kind: Service
metadata:
  name: ng-deploy-80
spec:
  ports:
  - name: http
    port: 90
    targetPort: 80
    # 此端口必须处于未被监听的状态
    nodePort: 30012
    protocol: TCP
  type: NodePort
  selector:
    app: ng-deploy-80