kind: Service
apiVersion: v1
metadata: 
  labels:
    app: erp-tomcat-app-log-service-label
  name: erp-tomcat-app-log-service
  namespace: erp
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 40083
  selector:
    app: erp-tomcat-app-log-selector