kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: erp-tomcat-app-logdeployment-label
  name: erp-tomcat-app-log-deployment
  namespace:
    erp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erp-tomcat-app-log-selector
  template:
    metadata:
      labels:
        app: erp-tomcat-app-log-selector
    spec:
      containers:
        - name: erp-tomcat-app-log-container
          image: harbor.k8s.com/erp/tomcat-webapp-log:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          resources:
            limits:
              cpu: 1
              memory: "512Mi"
            requests:
              cpu: 500m
              memory: "512Mi"